function sld = slider(minValue,maxValue, initialValue)
    sld = uicontrol('Style', 'slider', ...
                'Min', minValue, ...
                'Max', maxValue, ...
                'Value', initialValue, ...
                'Position', [50, 20, 400, 20]); % [left, bottom, width, height]
end

