function FORCE_VECTOR = suspension_force_solver(force, force_coord, braking_moment, susp, clevi_point)
arguments
    force v3
    force_coord v3
    braking_moment double
    susp suspension
    clevi_point v3
end
    num_of_points = 21;
    zero_vector = v3(0,0,0);
    FORCE_VECTOR = zeros(1, num_of_points, like=zero_vector);

    
    %% Knuckle - Tierod      TODO: Falta implementar el par del freno
    tierod_direction = (susp.knuckle.coord(3) - clevi_point);
    knuckle_rotation_axis = susp.knuckle_rotation_axis();
    closest_point = point_line_projection(force_coord, knuckle_rotation_axis, susp.knuckle.coord(1)); % Closest point to rotation axis from the point of force-aplication
    radial_distance = force_coord - closest_point; % Distance from force to that point
    tangential_direction = (knuckle_rotation_axis ^ (radial_distance')); % Direction normal to the rotation around the knuckle rotation axis

    Moment = (force * tangential_direction) .* (radial_distance.') + braking_moment*(knuckle_rotation_axis * susp.wheel_direction()); % Calculated moment of the knuckle around the kingpin axis
    Tangential_tierod_force = Moment / susp.knuckle_rotation_radius(); % Tangential force generated by the tierod at the knuckle
    
    tangential_tierod_direction = ((susp.knuckle_radius()') ^ knuckle_rotation_axis)';
    Tierod_force = tierod_direction' .* (((tierod_direction') * tangential_tierod_direction ) * Tangential_tierod_force);
    
    FORCE_VECTOR(11) = Tierod_force; % Force at the knuckle generated by the tierod


    %% Knuckle - Wishbone Points
    AB = susp.knuckle.coord(2) - susp.knuckle.coord(1); % Distance from B to A
    AC = susp.knuckle.coord(3) - susp.knuckle.coord(1); % Distance from C to A
    BC = susp.knuckle.coord(3) - susp.knuckle.coord(2); % Distance from C to B
    AQ = force_coord - susp.knuckle.coord(1); % Distance from the force aplication to A
    BQ = force_coord - susp.knuckle.coord(2); % Distance from the force aplication to B
    
    C = Tierod_force;
    Q = force;
    s = ((susp.l_wishbone.coord(3) - susp.l_wishbone.coord(2)) ^ (susp.l_wishbone.coord(3) - susp.l_wishbone.coord(1)) )';
    ratio = s.z/s.x;
    outside_car_direction = v3(0,sign(susp.knuckle.coord(1).y),0);

    % The reverses
    BA = -AB;
    CA = -AC;
    CB = -BC;
    QA = -AQ;
    QB = -BQ;

    Bx = -(AQ.z*Q.x + AQ.x*Q.z + AC.z*C.x + AC.x*C.z + braking_moment*1000*(susp.wheel_direction()*outside_car_direction)) / (AB.z + AB.x*ratio); % Trabajando en N·mm
    Bz = Bx/ratio;
    By = -(Bx*s.x + Bz*s.z)/s.y;

    B = v3(Bx, By, Bz);
    A = - force - Tierod_force - B;

    FORCE_VECTOR(3) = B; % Force at the knuckle
    FORCE_VECTOR(6) = A; % Force at the knuckle

    %% Forces at lower harpoints
    force_lower_wishbone = -B;

    rear_wishbone_direction = (susp.l_wishbone.coord(2) - susp.l_wishbone.coord(3));
    d = rear_wishbone_direction';
    ratio = d.y / d.x;
    AC = susp.l_wishbone.coord(3) - susp.l_wishbone.coord(1);
    AB = susp.l_wishbone.coord(2) - susp.l_wishbone.coord(1);
    C = force_lower_wishbone;

    lower_rear_reaction_x = -(AC.x*C.y + AC.y*C.x ) / (AB.y + AB.x*ratio);
    B = d .* (lower_rear_reaction_x / d.x);

    FORCE_VECTOR(2) = B;
    FORCE_VECTOR(1) = - FORCE_VECTOR(2) - C;



    %% Knuckle
    


end
